export const WATCH_REGIONS = [
  { code: 'TR', flag: '🇹🇷', name: 'Türkiye'              },
  { code: 'US', flag: '🇺🇸', name: 'ABD'                  },
  { code: 'GB', flag: '🇬🇧', name: 'Birleşik Krallık'     },
  { code: 'DE', flag: '🇩🇪', name: 'Almanya'              },
  { code: 'FR', flag: '🇫🇷', name: 'Fransa'               },
  { code: 'IT', flag: '🇮🇹', name: 'İtalya'               },
  { code: 'ES', flag: '🇪🇸', name: 'İspanya'              },
  { code: 'NL', flag: '🇳🇱', name: 'Hollanda'             },
  { code: 'SE', flag: '🇸🇪', name: 'İsveç'                },
  { code: 'NO', flag: '🇳🇴', name: 'Norveç'               },
  { code: 'DK', flag: '🇩🇰', name: 'Danimarka'            },
  { code: 'FI', flag: '🇫🇮', name: 'Finlandiya'           },
  { code: 'PL', flag: '🇵🇱', name: 'Polonya'              },
  { code: 'CA', flag: '🇨🇦', name: 'Kanada'               },
  { code: 'AU', flag: '🇦🇺', name: 'Avustralya'           },
  { code: 'JP', flag: '🇯🇵', name: 'Japonya'              },
  { code: 'KR', flag: '🇰🇷', name: 'Güney Kore'           },
  { code: 'IN', flag: '🇮🇳', name: 'Hindistan'            },
  { code: 'BR', flag: '🇧🇷', name: 'Brezilya'             },
  { code: 'MX', flag: '🇲🇽', name: 'Meksika'              },
  { code: 'AR', flag: '🇦🇷', name: 'Arjantin'             },
  { code: 'PT', flag: '🇵🇹', name: 'Portekiz'             },
  { code: 'SA', flag: '🇸🇦', name: 'Suudi Arabistan'      },
  { code: 'AE', flag: '🇦🇪', name: 'Birleşik Arap Emirlikleri' },
]
